-- MySQL Script generated by MySQL Workbench
-- Sat Nov 25 01:28:22 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_campeonato
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_campeonato
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_campeonato` DEFAULT CHARACTER SET utf8 ;
USE `bd_campeonato` ;

-- -----------------------------------------------------
-- Table `bd_campeonato`.`organizacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_campeonato`.`organizacao` (
  `id` INT(11) NOT NULL AUTO_INCREMENT ,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_campeonato`.`time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_campeonato`.`time` (
  `id` INT(11) NOT NULL AUTO_INCREMENT ,
  `nome` VARCHAR(45) NOT NULL,
  `jogador1` VARCHAR(45) NOT NULL,
  `jogador2` VARCHAR(45) NOT NULL,
  `jogador3` VARCHAR(45) NOT NULL,
  `jogador4` VARCHAR(45) NOT NULL,
  `jogador5` VARCHAR(45) NOT NULL,
  `jogador6` VARCHAR(45) NULL,
  `jogador7` VARCHAR(45) NULL,
  `jogador8` VARCHAR(45) NULL,
  `jogador9` VARCHAR(45) NULL,
  `jogador10` VARCHAR(45) NULL,
  `organizacao_id` INT NOT NULL,
  `pago` VARCHAR(45) NULL DEFAULT 'nao',
  PRIMARY KEY (`id`),
  INDEX `fk_Time_Organizacao1_idx` (`organizacao_id` ASC),
  CONSTRAINT `fk_Time_Organizacao1`
  FOREIGN KEY (`organizacao_id`)
  REFERENCES `bd_campeonato`.`organizacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_campeonato`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_campeonato`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `bd_campeonato`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_campeonato`.`grupo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT ,
  `nome` VARCHAR(45) NULL,
  `time_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Grupos_Time_idx` (`time_id` ASC),
  CONSTRAINT `fk_Grupos_Time`
  FOREIGN KEY (`time_id`)
  REFERENCES `bd_campeonato`.`time` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
